// Run with: bun generate.js (or node generate.js)
// Produces data.js with biblical verses and tao strophes.

import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// --- Parse KJV: Psalms + Song of Solomon ---
const kjvContent = readFileSync(join(__dirname, "kjv.txt"), "utf-8");
const kjvLines = kjvContent.split("\n").slice(2); // skip 2 header lines
const biblicalVerses = [];

for (const line of kjvLines) {
  const tabIdx = line.indexOf("\t");
  if (tabIdx === -1) continue;
  const reference = line.slice(0, tabIdx).trim();
  const text = line.slice(tabIdx + 1).trim();
  if (!reference || !text) continue;
  const match = reference.match(/^(.+?)\s+\d+:\d+$/);
  if (!match) continue;
  const book = match[1];
  if (book !== "Psalm" && book !== "Song of Solomon") continue;
  biblicalVerses.push({ reference, text, book });
}

// --- Parse Tao: extract strophes (blank-line-separated groups within each passage) ---
const taoContent = readFileSync(
  join(__dirname, "tao_te_ching_leguin.txt"),
  "utf-8"
);
const SEPARATOR = "============================================================";
const blocks = taoContent.split(SEPARATOR).map((b) => b.trim());
const taoStrophes = [];

for (let i = 0; i < blocks.length - 1; i++) {
  const headerMatch = blocks[i].match(/^CHAPTER (\d+): (.+)/);
  if (!headerMatch) continue;

  const number = parseInt(headerMatch[1], 10);
  const title = headerMatch[2];
  const body = blocks[i + 1];

  const passageStart = body.indexOf("PASSAGE:");
  if (passageStart === -1) continue;

  const commentaryStart = body.indexOf("COMMENTARY:");
  const passageText =
    commentaryStart !== -1
      ? body.slice(passageStart + "PASSAGE:".length, commentaryStart).trim()
      : body.slice(passageStart + "PASSAGE:".length).trim();

  // Split passage into strophes by blank lines
  const rawStrophes = passageText.split(/\n\s*\n/);
  for (const raw of rawStrophes) {
    const lines = raw
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l.length > 0);
    if (lines.length > 0) {
      taoStrophes.push({ chapter: number, title, lines });
    }
  }
}

// --- Write data.js ---
const output = `// Auto-generated by generate.js — do not edit by hand.
const BIBLICAL_VERSES = ${JSON.stringify(biblicalVerses)};
const TAO_STROPHES = ${JSON.stringify(taoStrophes)};
`;

writeFileSync(join(__dirname, "data.js"), output);
console.log(
  `Written data.js: ${biblicalVerses.length} biblical verses, ${taoStrophes.length} tao strophes.`
);
