// Oracles of Astrampsychus - Complete Data
// From "Ancient Greek Popular Literature" translated by Randall Stewart and Kenneth Morrell

// Questions: numbered 12-103
const questions = {
  12: "Will I sail safely?",
  13: "Is it a time to consult the oracle?",
  14: "Will I serve in the army?",
  15: "Will I have a share in the business?",
  16: "Will I advance in office?",
  17: "Will I go out of town?",
  18: "Is it to my advantage to enter into an agreement?",
  19: "Will I be successful?",
  20: "Will I purchase what is offered?",
  21: "Will I marry, and will it be to my advantage?",
  22: "Can I be harmed in the business affair?",
  23: "Will I move from this place?",
  24: "Is my wife having a baby?",
  25: "Will I be able to borrow money?",
  26: "Will I pay back what I owe?",
  27: "Will the traveler return?",
  28: "Will I soon give an accounting?",
  29: "Am I be safe from prosecution?",
  30: "Will I rear the baby?",
  31: "Will I be harmed in the business affair?",
  32: "Will I be freed from servitude?",
  33: "Will I inherit from my father?",
  34: "Will I inherit from my mother?",
  35: "Will I be an official in this matter?",
  36: "Will I find the fugitive?",
  37: "Will I have a good end?",
  38: "Will I inherit from a friend?",
  39: "Will I be an agoranomos?",
  40: "Will I find what I have lost?",
  41: "Will I be a teacher?",
  42: "Will I survive the sickness?",
  43: "Will I open a workshop?",
  44: "Will I have a long life?",
  45: "Will I obtain the petition?",
  46: "Will I come to terms with my masters?",
  47: "Will I beget children?",
  48: "Will I inherit from my parents?",
  49: "Will I get the dowry?",
  50: "Will I retain possession of my property?",
  51: "Will I argue my case?",
  52: "Will I inherit from my wife?",
  53: "Will I be safe if informed against?",
  54: "Will the one who is sick survive?",
  55: "Will I get the woman I desire?",
  56: "Will I be released from detention",
  57: "Will I sell my cargo?",
  58: "If I lend money, will I lose it?",
  59: "Is my wife going to miscarry?",
  60: "Will I be an oikonomos?",
  61: "Will I take a lease and will it benefit me?",
  62: "Will I have an inheritance from someone?",
  63: "Will I defeat my opponent in the trial?",
  64: "Am I going to see a death?",
  65: "Will I be a general?",
  66: "WIll I be made a cleric?",
  67: "Will I get the call to office?",
  68: "Will I have hope of trust?",
  69: "Will I win if I put down a deposit?",
  70: "Am I going to marry my girlfriend?",
  71: "Will I get my deposit back?",
  72: "Will I get provisions?",
  73: "Will I remain where I'm going?",
  74: "Am I going to be sold?",
  75: "Will I get some benefit from my friend?",
  76: "Is it granted to me to have dealings with another?",
  77: "Will I be restored to my place?",
  78: "Will I get an escort?",
  79: "Will I get the money?",
  80: "Is the traveler alive?",
  81: "Will I profit from the undertaking?",
  82: "Are my belongings going to be sold at auction?",
  83: "Will I find a way to sell?",
  84: "Will I buy the thing I have in mind?",
  85: "Will I be prosperous?",
  86: "Will I be banished?",
  87: "Will I be an ambassador?",
  88: "Will I be a senator?",
  89: "Will the fugitive escape my detection?",
  90: "Will I be estranged from my wife?",
  91: "Have I been poisoned?",
  92: "Will I get a bequest?",
  93: "Will I finish what I undertake?",
  94: "Will I be able to see my homeland?",
  95: "Will I become a decemvir?",
  96: "Will I get free from my lot?",
  97: "Will my wife stay with me?",
  98: "Will I remain an elder?",
  99: "Will I buy land or a house?",
  100: "Will I be caught as an adulterer presently?",
  101: "Will I become a bishop?",
  102: "Will I be estranged from my girlfriend?",
  103: "Will the one who is detained be set free?",
};

// Table of Correspondences
// Maps (question number + lot number) to decade number
const correspondenceTable = {
  13: 20, 14: 101, 15: 44, 16: 98, 17: 19, 18: 93, 19: 79, 20: 35, 21: 8, 22: 46,
  23: 24, 24: 27, 25: 71, 26: 18, 27: 15, 28: 37, 29: 56, 30: 102, 31: 38, 32: 34,
  33: 3, 34: 68, 35: 76, 36: 50, 37: 53, 38: 4, 39: 96, 40: 40, 41: 21, 42: 23,
  43: 70, 44: 99, 45: 62, 46: 31, 47: 33, 48: 5, 49: 45, 50: 100, 51: 41, 52: 39,
  53: 11, 54: 74, 55: 10, 56: 49, 57: 83, 58: 94, 59: 86, 60: 61, 61: 52, 62: 52,
  63: 6, 64: 42, 65: 78, 66: 48, 67: 59, 68: 7, 69: 1, 70: 95, 71: 90, 72: 17,
  73: 22, 74: 80, 75: 60, 76: 84, 77: 43, 78: 14, 79: 55, 80: 30, 81: 64, 82: 58,
  83: 85, 84: 87, 85: 26, 86: 66, 87: 67, 88: 9, 89: 72, 90: 13, 91: 81, 92: 12,
  93: 57, 94: 29, 95: 25, 96: 89, 97: 77, 98: 54, 99: 65, 100: 73, 101: 32, 102: 16,
  103: 2, 104: 51, 105: 28, 106: 36, 107: 63, 108: 82, 109: 88, 110: 91, 111: 92, 112: 97,
  113: 103, 114: 47, 115: 69
};

// Decades of Answers (1-103, each with answers 1-10)
const decades = {
  1: {
    1: "You won't have hope of trust.",
    2: "You won't get the call to office just now.",
    3: "You'll be made a cleric, but late.",
    4: "You'll be a general, you'll thrive, and you'll be distinguished.",
    5: "You're going to see a death and to rejoice presently.",
    6: "You'll have satisfaction. You'll win. Do battle.",
    7: "You'll have an inheritance with another trial.",
    8: "If you take a lease, you'll suffer a great loss.",
    9: "You'll be an oikonomos and you'll be envied by someone.",
    10: "She'll miscarry with peril, but she'll be safe."
  },
  2: {
    1: "You'll be reconciled with your wife and with your girlfriend.",
    2: "It's not your fate to be a bishop. Don't hope for it.",
    3: "It's your lot—and a putrid one—to be an adulterer.",
    4: "You'll buy the land or house that you want.",
    5: "You'll remain an elder until death.",
    6: "Your wife won't stay with you. Marry someone else.",
    7: "You'll get free from your lot if you want to.",
    8: "You'll become a decemvir soon.",
    9: "You'll be able to see your homeland in time.",
    10: "You won't finish what you're considering. Don't expect to."
  },
  3: {
    1: "You won't be freed just yet.",
    2: "You'll be harmed, but not excessively. Don't be upset.",
    3: "With effort the baby will survive.",
    4: "You won't be safe from charges just yet. Be concerned.",
    5: "You'll soon give an accounting.",
    6: "The traveler will return in good health.",
    7: "You'll soon pay what you owe and you'll be happy.",
    8: "You won't be able to borrow money just yet.",
    9: "She'll have a baby and be in peril up to the point of death.",
    10: "You won't soon move from your place. Don't fear."
  },
  4: {
    1: "You won't have a good end.",
    2: "You won't find the fugitive now.",
    3: "You'll be an official and succeed.",
    4: "You'll inherit from your mother.",
    5: "You'll inherit from your father.",
    6: "You won't be freed just yet. Don't expect it.",
    7: "You'll be harmed up to the point of words.",
    8: "The baby will grow up.",
    9: "You won't be safe from the accusation.",
    10: "You'll give an accounting, but not for a while."
  },
  5: {
    1: "You won't beget children now. It's not to your advantage.",
    2: "You won't come to terms with your masters now.",
    3: "Submit the petition. You'll be successful.",
    4: "You'll have a long life—and a good one.",
    5: "You'll open a workshop to your benefit.",
    6: "You'll survive your sickness, but it will take a while.",
    7: "You'll be a teacher in a foreign country and become rich.",
    8: "You won't find what you have lost now.",
    9: "You'll be an agoranomos, but not just yet.",
    10: "You won't inherit from your friend; you'll be forsaken."
  },
  6: {
    1: "You won't have an inheritance.",
    2: "You'll take a lease and profit greatly.",
    3: "You'll serve well as an oikonomos and be distinguished.",
    4: "She'll prevail in her future pregnancy.",
    5: "Don't make the loan because you'll lose the money.",
    6: "You won't sell your cargo right away.",
    7: "You'll be freed from detention now.",
    8: "You'll get the woman you want and then have second thoughts.",
    9: "The sick person will be in danger.",
    10: "Through your friends you'll be safe from the allegation."
  },
  7: {
    1: "You'll get the call to office.",
    2: "You won't be made a cleric.",
    3: "You'll be a general and be in peril.",
    4: "You're going to see a death now.",
    5: "You'll win soon. Do battle rejoicing.",
    6: "You'll have an inheritance, but not all of it.",
    7: "You won't take a lease just now, since it won't benefit you.",
    8: "You'll be an oikonomos soon and you'll be distinguished.",
    9: "Your wife won't miscarry. Don't worry.",
    10: "If you lend the money, make the loan once you have collateral."
  },
  8: {
    1: "You won't purchase what is offered.",
    2: "You'll succeed at last, when you have grown a little older.",
    3: "Having come to an agreement, you'll profit greatly.",
    4: "Don't travel out of town. It's not to your advantage.",
    5: "You'll advance after a time as you desire.",
    6: "You'll have a share and fail.",
    7: "If you serve in the army, you'll regret it.",
    8: "You don't have the hour for inquiring.",
    9: "If you sail soon, you'll be in danger.",
    10: "The one who is detained will be set free in time."
  },
  9: {
    1: "You have not erred. Become an ambassador.",
    2: "You won't be banished, but you'll be maltreated to some extent.",
    3: "You'll never be prosperous.",
    4: "You'll buy the thing you have in mind and sell it after you've used it.",
    5: "If you sell just now, you'll suffer.",
    6: "Your belongings won't be sold at auction. Don't be afraid.",
    7: "You'll profit from the undertaking a little.",
    8: "The traveler isn't alive. He was poisoned.",
    9: "You'll get the money with much trouble.",
    10: "You'll get an escort presently."
  },
  10: {
    1: "He will recover from the sickness soon.",
    2: "You won't be safe from the allegation. Circumvent it.",
    3: "You'll inherit from your wife, because she'll die first.",
    4: "Don't argue your case right now. You'll lose.",
    5: "Not all of your property will remain in your possession.",
    6: "You'll get the dowry after a time.",
    7: "You'll inherit from your parents, but not as the sole heir.",
    8: "You'll beget children, rear them, and bury them.",
    9: "With effort you'll come to terms with your masters.",
    10: "You'll submit your petition and benefit."
  },
  11: {
    1: "You won't inherit from your wife.",
    2: "Argue your case right now. You'll win.",
    3: "All of your property will remain in your possession.",
    4: "You won't obtain the dowry right away.",
    5: "In a short time, you'll inherit from your parents.",
    6: "You'll be blessed with children, but you'll be distressed by them.",
    7: "You won't come to terms with your masters now.",
    8: "You won't be successful with your petition right away.",
    9: "You'll have an average lifespan. Don't be upset. Pray instead.",
    10: "You'll open a workshop with a struggle."
  },
  12: {
    1: "You have been poisoned. Treat yourself.",
    2: "You won't be estranged from your wife until you die.",
    3: "The fugitive is escaping your detection now.",
    4: "You'll be a senator, but not just yet.",
    5: "You won't be an ambassador by yourself. Don't hope for it.",
    6: "You won't be banished. Don't be afraid.",
    7: "You won't be completely prosperous.",
    8: "You won't buy the thing you have in mind just yet.",
    9: "You'll sell to your detriment.",
    10: "Your belongings won't be sold at auction. Don't be afraid."
  },
  13: {
    1: "The fugitive won't escape your detection.",
    2: "You'll become a senator by means of a gift.",
    3: "You'll be an ambassador by yourself and you'll profit.",
    4: "You'll be banished for a time and you'll profit.",
    5: "You won't be prosperous.",
    6: "You won't buy it just yet. Get it out of your mind.",
    7: "You won't find a way to sell just now.",
    8: "Your belongings won't be sold at auction.",
    9: "You'll profit from the undertaking.",
    10: "The traveler is alive and healthy."
  },
  14: {
    1: "You won't be restored to your place.",
    2: "It's not granted to you to have dealings with another.",
    3: "You'll benefit from your friend's business.",
    4: "You'll be sold, but not just yet.",
    5: "You won't remain where you are going.",
    6: "You'll get provisions, but not just now.",
    7: "You'll get your deposit back.",
    8: "If you marry your girlfriend, you'll suffer.",
    9: "Put down a deposit. You'll win.",
    10: "You won't have hope of trust."
  },
  15: {
    1: "You won't pay back what you owe.",
    2: "You'll borrow money with collateral.",
    3: "Your wife will have a baby and it will survive.",
    4: "You'll move from your place for the worse.",
    5: "You'll be harmed, but only a little.",
    6: "You'll marry, but then you'll dissolve the marriage.",
    7: "You'll purchase what is offered and you'll suffer.",
    8: "You'll be successful finally. Don't worry.",
    9: "You'll come quickly to an agreement and profit.",
    10: "You'll go out of town suddenly and it will be for your good."
  },
  16: {
    1: "It's not your lot to be a bishop.",
    2: "You'll be caught in adultery soon.",
    3: "You'll buy the field or house that you want.",
    4: "You'll remain an elder until old age.",
    5: "Your wife won't stay with you. She's committing adultery.",
    6: "You'll get free from your lot with a fight.",
    7: "You'll become a decemvir soon.",
    8: "You'll be able to see your homeland to your advantage.",
    9: "You'll finish quickly what you undertake.",
    10: "You won't get a bequest. You've been discredited."
  },
  17: {
    1: "You won't get your deposit back.",
    2: "You won't marry your girlfriend now. She's become a prostitute.",
    3: "Don't put down a deposit. You'll be defeated.",
    4: "You'll have excellent hope of trust.",
    5: "You'll get the call to office.",
    6: "You'll be made a cleric.",
    7: "You won't be a general. It will be to your benefit.",
    8: "You're going to see a death that is advantageous.",
    9: "You'll win. Do battle to the end.",
    10: "You'll have an inheritance soon."
  },
  18: {
    1: "You won't be able to borrow money.",
    2: "Your wife will give birth to a fine baby and do well.",
    3: "You won't move from your place just yet.",
    4: "You won't be harmed. Don't be distressed.",
    5: "You'll marry and, though you desired the marriage, you'll dissolve it.",
    6: "You'll quickly purchase what is offered.",
    7: "You'll be successful as a result of your own efforts.",
    8: "You won't come to an agreement with anyone yet.",
    9: "You won't go out of town now. Wait.",
    10: "You'll advance to your good and be distinguished."
  },
  19: {
    1: "You won't advance just now.",
    2: "You'll share in the business well and benefit.",
    3: "You'll serve in the army with suffering and you'll regret it.",
    4: "Don't inquire. The day is adverse.",
    5: "You'll sail after being delayed.",
    6: "The one who is detained will be freed from his confinement.",
    7: "You'll be reconciled with your wife by force.",
    8: "You'll become a bishop and be profited.",
    9: "You'll be caught in adultery. Take heed.",
    10: "You won't buy the property now."
  },
  20: {
    1: "You won't sail well.",
    2: "The one who is detained will be set free.",
    3: "You'll be reconciled with your wife in a way you don't expect.",
    4: "You'll become a bishop in a way you don't expect.",
    5: "You'll be caught in adultery soon.",
    6: "You won't buy land now.",
    7: "Your girlfriend won't remain with you. She's getting married.",
    8: "Your wife will stay with you until old age.",
    9: "You'll get free from your girlfriend.",
    10: "You'll become a decemvir in a way you don't know."
  },
  21: {
    1: "You won't find what is lost.",
    2: "You won't be an agoranomos just yet. Wait.",
    3: "You'll inherit from your friend with a trial.",
    4: "You won't have a good end. It's up to you to inquire further.",
    5: "You won't find the fugitive now, but after a time.",
    6: "You'll be an official, and you'll be esteemed and honored.",
    7: "You'll inherit half of your mother's estate.",
    8: "You won't inherit from your father, because you'll die first.",
    9: "You won't be freed now, but after a time.",
    10: "You'll be harmed, but not just yet."
  },
  22: {
    1: "You'll get provisions.",
    2: "You won't get your deposit back.",
    3: "You won't be able to marry your girlfriend.",
    4: "Put down a deposit. You'll win.",
    5: "You'll have excellent hope of trust.",
    6: "You'll get the call to office.",
    7: "You'll be made a cleric, but not for a while.",
    8: "You'll be a general, you'll thrive, and you'll be distinguished.",
    9: "You're going to see two deaths that are unprofitable.",
    10: "You won't win for a while. Don't think about it."
  },
  23: {
    1: "You won't be able to be a teacher.",
    2: "You won't soon find what is lost.",
    3: "You'll soon be an agoranomos.",
    4: "You won't inherit from your friend. Don't hope for it.",
    5: "You'll have a good end.",
    6: "You won't find the fugitive. He has sailed away.",
    7: "It's your lot to be an official.",
    8: "You won't inherit from your mother. She'll bury you.",
    9: "You'll inherit a third of your father's estate.",
    10: "You won't be freed. Be silent."
  },
  24: {
    1: "You'll be harmed greatly.",
    2: "You'll marry and then be sorry because you'll have gained nothing.",
    3: "You'll purchase what is offered if you desire.",
    4: "You'll succeed, having inherited from others.",
    5: "You'll come to an agreement and benefit greatly.",
    6: "You'll go out of town and have second thoughts.",
    7: "You'll advance as a result of the unexpected.",
    8: "It's not to your advantage to have a share. You'll suffer losses.",
    9: "You'll serve in the army and you'll advance quickly.",
    10: "Wait today and inquire tomorrow."
  },
  25: {
    1: "You won't be able to see your homeland.",
    2: "You won't finish what you undertake.",
    3: "You'll get a bequest, but a small one.",
    4: "You haven't been poisoned, but you have been bewitched.",
    5: "You'll be estranged from your wife, but you'll be derided.",
    6: "The fugitive will escape your detection for a little while.",
    7: "You'll be a senator and a bankrupt fraud.",
    8: "You'll be an ambassador and you'll prosper, if you press for it.",
    9: "You won't be banished. Don't be afraid at all.",
    10: "You'll be prosperous and distinguished."
  },
  26: {
    1: "You'll buy the thing you have in mind.",
    2: "You won't find a way to sell and make a profit just now.",
    3: "Your belongings won't be sold at auction. Relax.",
    4: "You'll profit a little from the undertaking.",
    5: "The traveler is alive. Don't be distressed. He's coming.",
    6: "You'll get the money after a while.",
    7: "You won't get an escort just now.",
    8: "You'll be restored to your place.",
    9: "Don't have dealings with another just now. You'll be harmed.",
    10: "You won't get any benefit from your friend."
  },
  27: {
    1: "You won't move from your place.",
    2: "You won't be harmed. Don't be distressed. Pray instead.",
    3: "You'll suddenly marry a woman whom you know and want.",
    4: "You'll purchase with effort what is offered.",
    5: "You'll succeed as a consequence of your own efforts.",
    6: "You'll soon come to an agreement and profit greatly.",
    7: "You won't go out of town for a while.",
    8: "You'll advance suddenly when you don't realize it.",
    9: "Don't share in the business. It's not to your advantage.",
    10: "You'll serve, but not just yet."
  },
  28: {
    1: "You'll sail well.",
    2: "The one who is detained will be set free with effort.",
    3: "You'll be reconciled with your girlfriend and you'll be sorry.",
    4: "You'll become a bishop after you have worked a great deal.",
    5: "You won't be caught as an adulterer. Don't be distressed.",
    6: "You'll buy land and a house.",
    7: "You won't remain an elder.",
    8: "Your wife will stay with you if you wish.",
    9: "You won't get free from your lot until you die.",
    10: "You'll become a decemvir."
  },
  29: {
    1: "You'll finish what you undertake.",
    2: "You won't get a complete bequest.",
    3: "You haven't been poisoned. Don't be distressed.",
    4: "You won't be reconciled with your wife.",
    5: "The fugitive won't escape your detection.",
    6: "You'll be a senator, but not just yet.",
    7: "You'll be an ambassador, but not by yourself.",
    8: "You won't be banished. Don't be distressed.",
    9: "You'll become prosperous suddenly.",
    10: "You'll buy the thing you have in mind, if you want to."
  },
  30: {
    1: "You won't get the money just yet.",
    2: "You'll get an escort with much effort.",
    3: "You'll be restored to your place.",
    4: "You won't be able to have dealings with another.",
    5: "You won't benefit at all from your friend.",
    6: "You won't be sold just yet, but it won't benefit you.",
    7: "You won't remain where you are going.",
    8: "You won't get provisions.",
    9: "You won't get your deposit back.",
    10: "You'll marry your girlfriend and you'll suffer."
  },
  31: {
    1: "You'll submit your petition in vain.",
    2: "You won't have a long life.",
    3: "You'll eventually open a workshop.",
    4: "You'll survive your illness, if you take heed.",
    5: "You'll become a teacher suddenly.",
    6: "You won't find what is lost.",
    7: "You'll be an agoranomos and you'll benefit.",
    8: "You won't inherit from your friend. Don't expect it.",
    9: "You'll have a good end.",
    10: "You'll soon find the fugitive."
  },
  32: {
    1: "You won't be caught in adultery.",
    2: "You won't buy land or a house.",
    3: "You won't remain an elder.",
    4: "Your first wife won't stay with you.",
    5: "You'll get free from your lot.",
    6: "You won't become a decemvir just yet.",
    7: "You won't be able to see your homeland just now.",
    8: "You won't finish what you undertake.",
    9: "You won't get a bequest. Don't expect it.",
    10: "You've been poisoned. Treat yourself."
  },
  33: {
    1: "You won't come to terms with your masters.",
    2: "Don't submit your petition just yet.",
    3: "You'll have a long life and suffer pains in your feet.",
    4: "You won't open a workshop just yet.",
    5: "You'll survive your illness, for you've been called back.",
    6: "You won't be a teacher in your homeland.",
    7: "You won't find what is lost.",
    8: "Know well; you won't soon be an agoranomos.",
    9: "You won't inherit from your friend. You'll scoff.",
    10: "You won't have a good end. You'll ask for more."
  },
  34: {
    1: "You'll be harmed terribly.",
    2: "You'll rear the baby.",
    3: "You'll be safe from the accusation.",
    4: "You'll give an accounting. Don't be distressed.",
    5: "The traveler won't return. He has married.",
    6: "You won't pay back what you owe.",
    7: "You'll borrow money and immediately spend it.",
    8: "She'll have a baby girl with peril.",
    9: "You'll move from your place. Get packed.",
    10: "You won't be harmed. Don't be distressed."
  },
  35: {
    1: "You won't be successful.",
    2: "You'll suddenly come to an agreement and you'll profit.",
    3: "You won't go out of town for a while.",
    4: "You'll advance quickly to a good place.",
    5: "Don't share in the business. It's not to your advantage.",
    6: "If you serve, you'll be sorry.",
    7: "Now is not the time. Give up just now.",
    8: "Don't sail just yet. You'll be shipwrecked.",
    9: "The one who is detained will be set free soon.",
    10: "You won't be reconciled with your wife."
  },
  36: {
    1: "You won't get any benefit from your friend.",
    2: "Don't sail. I'm warning you.",
    3: "The one who is detained will be set free.",
    4: "You won't be estranged from your girlfriend.",
    5: "You won't become a bishop. Don't expect it.",
    6: "You won't be caught as an adulterer for the time being.",
    7: "You'll buy the property and it won't stay with you.",
    8: "You'll remain an elder.",
    9: "Your wife won't stay with you.",
    10: "You won't get free from your lot."
  },
  37: {
    1: "The traveler won't return.",
    2: "You'll now pay back what you owe.",
    3: "You'll borrow money and suffer. It won't last.",
    4: "She'll give birth to a boy with peril.",
    5: "You won't move from your place for a while.",
    6: "You won't be harmed. Don't be distressed.",
    7: "You'll marry a woman from your daily acquaintance.",
    8: "You'll purchase with effort what is offered.",
    9: "You'll succeed in everything.",
    10: "You'll come to an agreement and devote your time to the business."
  },
  38: {
    1: "The baby will survive for the good.",
    2: "You won't be safe from the accusation. You've been prejudged.",
    3: "You'll soon give an accounting for the good.",
    4: "The traveler won't return just yet. Don't expect him.",
    5: "You'll now pay back what you owe and you'll rejoice.",
    6: "No one will lend money to you just now. Wait.",
    7: "She'll have a baby girl who won't live long.",
    8: "You'll soon move from your place for the better.",
    9: "You'll suffer a loss at first, but in the end you'll have a profit.",
    10: "You'll be harmed in your first marriage. Persevere."
  },
  39: {
    1: "Argue your case.",
    2: "Your property will remain in your possession.",
    3: "You won't obtain the dowry unless you sue.",
    4: "You alone will inherit from your parents.",
    5: "You'll soon beget the children and be distressed by them.",
    6: "You won't come to terms with your masters now.",
    7: "You'll soon submit your petition.",
    8: "You'll have a long life and wealth. You'll ask for more.",
    9: "You won't open a workshop now. Wait.",
    10: "You'll recover from your illness quickly. Just be cheerful."
  },
  40: {
    1: "You won't be an agoranomos.",
    2: "You won't inherit from your friend. Why do you hope?",
    3: "You'll have a good end, but it will be short.",
    4: "You won't find the fugitive now.",
    5: "You have the favorable lot of an official.",
    6: "You'll inherit from your mother now.",
    7: "You'll never inherit from your father.",
    8: "You'll be freed with a good bequest.",
    9: "You won't be harmed. Don't be distressed at all.",
    10: "The baby will survive and grow quickly."
  },
  41: {
    1: "Your property won't remain in your possession.",
    2: "You won't obtain the dowry. Don't sue.",
    3: "You won't inherit from your parents. You'll die first.",
    4: "You won't beget children with her. Don't expect it.",
    5: "You'll come to terms with your masters after a while.",
    6: "You won't submit your petition soon. It will be to your advantage.",
    7: "After a time you'll succeed and grow old.",
    8: "You'll open a workshop and be rich.",
    9: "You won't recover from your illness.",
    10: "You won't be a teacher. Do something else."
  },
  42: {
    1: "You won't win. Keep silent.",
    2: "You'll have an inheritance when you are not hoping for it.",
    3: "You won't take a lease just now. Wait. Don't rush.",
    4: "You'll be an oikonomos and many people will bring charges against you.",
    5: "Your wife won't miscarry. Be happy.",
    6: "Don't lend the money. You'll recover it slowly.",
    7: "You'll sell your cargo and profit.",
    8: "You won't be released from detention. Persevere.",
    9: "You'll get the woman you desire and be rich.",
    10: "The sick person will be ill for some time, but he will regain his health."
  },
  43: {
    1: "It won't be granted to you to have dealings with another.",
    2: "You'll benefit a little from your friend.",
    3: "You'll be sold and you'll be sorry when you don't profit at all.",
    4: "Where you are going you won't remain, because it won't benefit you.",
    5: "You'll get provisions in part.",
    6: "You won't get your deposit back.",
    7: "It won't benefit you to marry your girlfriend.",
    8: "Don't put down a deposit. You'll be defeated.",
    9: "You'll have very excellent hope of trust.",
    10: "You won't get the call to office now."
  },
  44: {
    1: "It isn't granted to you to serve in the army.",
    2: "Inquire and hear the truth.",
    3: "You'll sail soon and you'll suffer bad weather.",
    4: "The one who is detained will be set free presently.",
    5: "You'll be reconciled with your wife and you'll be sorry.",
    6: "You'll become a bishop when you have grown old.",
    7: "You'll be caught in adultery and you'll be punished.",
    8: "You won't buy the property. Don't expect it.",
    9: "Your girlfriend won't remain with you. She desires someone else.",
    10: "Your wife will stay with you until old age."
  },
  45: {
    1: "You'll inherit from your parents.",
    2: "You'll be the father of a boy and a girl and you'll rejoice.",
    3: "You'll come to terms with your masters and benefit.",
    4: "You'll submit your petition in vain.",
    5: "You won't have a long life. Put your affairs in order.",
    6: "You won't open a workshop. It's not granted to you.",
    7: "You'll recover from your illness, but it will take some time.",
    8: "You'll become a teacher and succeed in the business.",
    9: "You'll find what is lost now. Give it some thought.",
    10: "You won't be an agoranomos. You'll be hindered."
  },
  46: {
    1: "You won't marry just now.",
    2: "You won't purchase what is offered.",
    3: "You'll succeed as a consequence of your own labors.",
    4: "You won't come to an agreement. Don't do it.",
    5: "You'll go out of town suddenly and benefit greatly.",
    6: "You'll advance when you're not expecting it.",
    7: "You'll have a share in the business, you'll suffer, and you'll be sorry.",
    8: "You'll serve in the army and advance quickly.",
    9: "Ask with faith and hear the truth.",
    10: "You'll sail well after being delayed."
  },
  47: {
    1: "You'll be safe from the accusation by means of a weighty appeal.",
    2: "You'll give an accounting after a while.",
    3: "The traveler will return soon in good spirits.",
    4: "You'll pay back in part what you owe. Don't be distressed.",
    5: "You'll borrow money with collateral and, at the right time, tear it up.",
    6: "She'll have an unprofitable baby. Don't be distressed.",
    7: "You'll move from your place. Get ready. Be happy.",
    8: "You can be harmed. Be afraid and look out for yourself.",
    9: "You'll marry and, filled with regret, you'll blame yourself.",
    10: "You won't purchase what is offered, dear friend."
  },
  48: {
    1: "You'll never be a general.",
    2: "You're not going to see a death now. Don't be distressed.",
    3: "You'll win. Do battle to the death.",
    4: "You'll have an inheritance and you'll die soon.",
    5: "You'll take a lease and profit greatly.",
    6: "You'll be an oikonomos, you'll be charged, and you'll be begrudged.",
    7: "She won't miscarry. Don't be afraid; pray instead.",
    8: "You'll lend the money and gratefully recover it.",
    9: "You'll sell your cargo without a problem.",
    10: "You'll be released from detention. Be cheerful."
  },
  49: {
    1: "You'll get the woman you want.",
    2: "The sick person will recover with considerable effort.",
    3: "You won't be safe from the allegation. Circumvent it.",
    4: "You'll inherit from your wife, but you won't be the sole heir.",
    5: "Don't argue your case just yet. You'll lose.",
    6: "Your property will remain in your possession.",
    7: "You won't get the dowry.",
    8: "You alone will inherit from your parents.",
    9: "You'll beget the children and find great happiness in them.",
    10: "You won't come to terms with your masters just yet."
  },
  50: {
    1: "You won't be able to be an official now.",
    2: "You'll inherit half of your mother's estate.",
    3: "You won't inherit from your father. Don't hope for it.",
    4: "You won't be freed just yet, but after a time.",
    5: "You won't be harmed. Don't be distressed, but persevere.",
    6: "The baby will survive with toil.",
    7: "You'll be safe from the accusation through a good friend.",
    8: "You'll soon give an accounting for the good.",
    9: "The traveler will return in good health.",
    10: "You won't pay back what you owe just yet. Wait."
  },
  51: {
    1: "The one who is detained won't be set free.",
    2: "You'll be estranged from your girlfriend presently.",
    3: "You'll become a bishop soon and you'll be sorry.",
    4: "You'll be caught as an adulterer and you won't suffer at all.",
    5: "You'll buy the property you desire.",
    6: "You'll remain an elder until old age.",
    7: "Your wife won't stay with you, since she's committing adultery.",
    8: "You'll get free from your lot. See to it.",
    9: "You'll become a decemvir in a hurry.",
    10: "You won't see your homeland. Count on it."
  },
  52: {
    1: "If you take a lease just now, you'll suffer a loss.",
    2: "Very soon you'll serve well as an oikonomos.",
    3: "She'll miscarry and be in danger. Take heed.",
    4: "You'll lend the money; eventually you'll recover it with a fight.",
    5: "You'll sell your cargo quickly and be pleased.",
    6: "You'll be released from detention quickly.",
    7: "You'll get the woman you desire to your ill.",
    8: "The sick person will recover with risk.",
    9: "You'll be safe from the allegation by means of a weighty appeal.",
    10: "You won't inherit from your wife. Don't hope for it."
  },
  53: {
    1: "You won't find the fugitive.",
    2: "You'll be an official and succeed and be distinguished.",
    3: "You alone will inherit from your mother.",
    4: "You won't inherit from your father. You'll die first.",
    5: "You'll be freed with an appeal once you've paid money.",
    6: "You'll be harmed terribly, but don't worry.",
    7: "The baby won't live. It will die soon.",
    8: "You won't be safe from the accusation. Make preparations.",
    9: "You'll soon give an accounting and you'll benefit.",
    10: "The traveler won't return because he's busy."
  },
  54: {
    1: "Your wife won't stay with you.",
    2: "You won't be able to get free from your lot.",
    3: "You won't become a decemvir. Don't hope for it.",
    4: "You'll see your homeland very soon.",
    5: "You won't finish what you undertake.",
    6: "You'll get a bequest to your great detriment.",
    7: "You have not been poisoned, but you have been bewitched.",
    8: "You won't be estranged from your wife. Persevere.",
    9: "The fugitive will escape your detection for a little while.",
    10: "You won't be a senator for a while. Wait."
  },
  55: {
    1: "You won't get an escort.",
    2: "You'll be restored to your place.",
    3: "You'll have dealings with another and you'll profit from the works of others.",
    4: "You'll get a great benefit from your friend.",
    5: "You won't be sold. It won't benefit you. Stand fast.",
    6: "You'll stay where you're going for a short season.",
    7: "You'll get the provisions after a while.",
    8: "You'll get your deposit back without peril.",
    9: "You won't marry your girlfriend. Don't ramble.",
    10: "If you put down a deposit, you'll be worsted."
  },
  56: {
    1: "You'll give an accounting.",
    2: "The traveler won't return just yet.",
    3: "You'll now pay back what you owe, if you wish.",
    4: "You won't be able to borrow money just yet. Wait.",
    5: "She'll give birth with great peril.",
    6: "You'll move from your place for the better.",
    7: "You can be harmed a little, but don't be distressed.",
    8: "You won't marry just yet. Wait. It will be to your advantage.",
    9: "You'll purchase what is offered and rejoice.",
    10: "You'll soon succeed for the better."
  },
  57: {
    1: "You won't get a bequest. Don't expect it.",
    2: "You've been poisoned. Treat yourself.",
    3: "You'll be reconciled with your wife and you'll be sorry.",
    4: "The fugitive will escape your detection for a season.",
    5: "You won't be a senator just yet. Don't think about it.",
    6: "You won't be an ambassador by yourself since it won't benefit you.",
    7: "You won't be banished. Don't be afraid. Be cheerful.",
    8: "You'll be prosperous and pleasing.",
    9: "You'll buy the thing you have in mind and you'll be sorry.",
    10: "You won't find a way to sell just now. Wait."
  },
  58: {
    1: "You'll profit a little from the undertaking.",
    2: "The traveler is alive and will return after a time.",
    3: "You'll get the money after a time.",
    4: "You won't get an escort just now.",
    5: "You'll be restored to your place.",
    6: "If you have dealings with another, you'll be harmed.",
    7: "You'll benefit from your friend.",
    8: "You won't be sold to your benefit.",
    9: "You'll remain where you are going if you hurry.",
    10: "You'll get provisions—and in a good way."
  },
  59: {
    1: "You won't be made a cleric.",
    2: "You won't be a general just now. Don't hope for it.",
    3: "You're not going to see a death.",
    4: "You won't win completely. Don't hope for it.",
    5: "You'll have an inheritance, but you won't be the sole heir.",
    6: "You'll take a lease and be greatly enriched.",
    7: "You won't be an oikonomos just now. It's not granted to you.",
    8: "She won't miscarry. Don't be afraid.",
    9: "Don't lend the money. Don't be trusting lest you have regrets.",
    10: "You'll sell your cargo without a problem."
  },
  60: {
    1: "You'll be sold, but not just yet.",
    2: "You'll remain where you're going for a short while.",
    3: "You'll get provisions now—and good ones.",
    4: "You'll get your deposit back.",
    5: "You'll marry your girlfriend, but not now.",
    6: "Put down a deposit. You'll win and you'll profit.",
    7: "You won't have hope of trust at all.",
    8: "You'll get the call to office quickly.",
    9: "You'll be made a cleric after a while.",
    10: "You won't ever be a general. Don't hope for it."
  },
  61: {
    1: "She'll miscarry and she'll be in danger.",
    2: "You'll lend as much money as you wish once you have collateral.",
    3: "You'll sell your cargo eventually. Don't despair.",
    4: "You won't be released from detention. Wait.",
    5: "You won't get the woman you desire.",
    6: "The sick person will recover after being ill for a long time.",
    7: "You'll be safe from the allegation through your friends.",
    8: "You won't inherit from your wife.",
    9: "State your case soon. You'll win. Fight it out.",
    10: "Your property won't remain in your possession for very long."
  },
  62: {
    1: "You won't have a long life.",
    2: "You won't open a workshop just yet.",
    3: "You won't recover from your sickness. Settle your affairs.",
    4: "You won't be a teacher. Do something else.",
    5: "You won't find what is lost now.",
    6: "You won't be an agoranomos just yet. Don't hope for it.",
    7: "You won't inherit from your friend now.",
    8: "You won't have a good end. Help yourself.",
    9: "You won't find the fugitive now.",
    10: "You won't be able to be an official just yet, but after a time."
  },
  63: {
    1: "You'll serve in the army to your detriment.",
    2: "You'll work with toil and much exertion.",
    3: "You'll sail well now and you'll have great enjoyment.",
    4: "The one who is detained won't be set free just now.",
    5: "You'll be reconciled with your wife to your benefit.",
    6: "It's not your fate to be a bishop. Don't hope for it.",
    7: "You're not an adulterer, but your wife loves another man.",
    8: "You won't buy land or a house just now.",
    9: "You won't remain an elder. You'll have very bad luck.",
    10: "Your wife won't stay with you."
  },
  64: {
    1: "The traveler is not safe.",
    2: "Concerning the money, send away quickly.",
    3: "You won't get an escort in the way you want.",
    4: "You won't be restored to your place.",
    5: "You'll benefit, if you have dealings with another.",
    6: "You won't have a benefit in your friend.",
    7: "Where you'll be purchased, you'll have regrets.",
    8: "You'll remain where you're going and you'll fare well.",
    9: "You'll come to terms in the matter of the provisions.",
    10: "You won't get your deposit back."
  },
  65: {
    1: "You won't remain an elder.",
    2: "Your wife won't stay with you until old age.",
    3: "You won't get free from your lot until you die.",
    4: "You'll become a decemvir very quickly.",
    5: "You won't be able to see your homeland.",
    6: "You'll finish quickly what you undertake.",
    7: "You'll get a bequest, but a little one.",
    8: "You've been poisoned. Treat yourself.",
    9: "You'll never be estranged from your wife.",
    10: "The fugitive will escape your detection for a little while."
  },
  66: {
    1: "You'll be prosperous.",
    2: "You won't buy what you have in mind, since it won't be to your benefit.",
    3: "You'll sell and you'll profit a great deal.",
    4: "Your belongings will be sold at auction and you'll acquire others.",
    5: "You'll profit from the undertaking a little.",
    6: "The traveler is alive and will return in good health.",
    7: "You'll get part of the money.",
    8: "You won't get an escort just now.",
    9: "You won't be restored to your place.",
    10: "If you have dealings with another, you'll be harmed."
  },
  67: {
    1: "You'll be banished for a little while.",
    2: "You won't be completely prosperous.",
    3: "You'll buy what you have in mind and you'll be happy with it.",
    4: "You'll find a way to sell—late, but well.",
    5: "Your belongings won't be sold at auction. Don't be afraid.",
    6: "You'll profit from the undertaking a great deal.",
    7: "The traveler is not alive. He won't return.",
    8: "You'll get the money presently.",
    9: "You won't get an escort now.",
    10: "You won't be restored to your place."
  },
  68: {
    1: "You won't inherit from your father.",
    2: "You won't be freed just yet. Don't expect it.",
    3: "You won't be harmed. Don't be afraid, but rather be happy.",
    4: "The baby will survive with toil.",
    5: "You'll be safe from the accusation by means of an appeal.",
    6: "You'll give an accounting freely.",
    7: "The traveler, having been delayed, will return. Be happy.",
    8: "You won't pay back what you owe just yet, but after a while.",
    9: "You'll eventually borrow money from the person you desire.",
    10: "She'll have a baby that is unprofitable."
  },
  69: {
    1: "You'll sail now.",
    2: "The one who is detained will be set free now.",
    3: "You'll be reconciled with your wife after a time.",
    4: "It's not your lot to be a bishop. Don't hope for it.",
    5: "You won't be caught as an adulterer.",
    6: "You'll buy land or a house.",
    7: "Your wife will remain with you since she has self-control.",
    8: "Your wife won't stay with you. She has a boyfriend.",
    9: "You'll get free from your girlfriend, because you'll be jealous of her.",
    10: "You won't ever become a decemvir."
  },
  70: {
    1: "You'll recover from your illness.",
    2: "You won't be a teacher. Do something else.",
    3: "You'll find what is lost quickly and be happy.",
    4: "You'll be an agoranomos and benefit greatly.",
    5: "You'll inherit half of your friend's estate.",
    6: "You'll have a good end. Just pray.",
    7: "You'll find the fugitive soon.",
    8: "You'll be an official, you'll succeed, and you'll be honored.",
    9: "You won't inherit from your mother. That's reserved for someone else.",
    10: "You alone will inherit from your father."
  },
  71: {
    1: "She'll have a baby with peril.",
    2: "You'll suddenly move from your place for the better.",
    3: "You'll be harmed in this affair, but in the other you'll benefit.",
    4: "You can marry to your benefit, if you hurry.",
    5: "You won't purchase what is offered. You don't have the means.",
    6: "You'll succeed at last and be master of the household.",
    7: "You'll come to an agreement and profit through others.",
    8: "You'll go out of town suddenly and profit.",
    9: "You won't advance just yet. Don't expect it.",
    10: "If you share in the business, you'll suffer greatly."
  },
  72: {
    1: "You won't be a senator.",
    2: "You won't be an ambassador by yourself since it won't benefit you.",
    3: "You won't be banished. Don't be afraid.",
    4: "You won't be prosperous at all.",
    5: "You'll buy the thing you have in mind and you'll be sorry.",
    6: "You'll find a way to sell after a while.",
    7: "Your belongings will be sold at auction. Take heed.",
    8: "You'll profit from the undertaking. Work at it.",
    9: "The traveler is returning with a good friend.",
    10: "You won't get all of the money."
  },
  73: {
    1: "You won't buy land or a house.",
    2: "You'll remain an elder until old age.",
    3: "Your wife won't stay with you. She's committing adultery.",
    4: "You'll get free from your lot in your old age.",
    5: "You'll become a decemvir suddenly.",
    6: "You'll be able to see your homeland, but late.",
    7: "You'll finish quickly what you undertake.",
    8: "You'll get a bequest, but a little one.",
    9: "You haven't been poisoned. Why are you being irrational?",
    10: "You won't be estranged from your wife. Relax."
  },
  74: {
    1: "You won't be safe from the allegation.",
    2: "You alone will inherit from your wife.",
    3: "Argue your case. You'll win. Fight it out.",
    4: "Your property will not remain in your possession until old age.",
    5: "You won't get the dowry. You'll find nothing.",
    6: "You won't inherit from your parents. You're hated.",
    7: "You won't beget children soon. Don't expect it to happen.",
    8: "You'll come to terms with your masters and be treated with affection.",
    9: "Submit your petition. You'll obtain whatever you need.",
    10: "You'll have a long life—and a very good one."
  },
  75: {
    1: "You won't be an oikonomos.",
    2: "She'll miscarry and be in danger up to the point of death.",
    3: "If you lend money, you'll recover it slowly.",
    4: "You won't sell your cargo quickly.",
    5: "You'll be released from detention right away.",
    6: "You'll get the woman you desire to your ill.",
    7: "The sick person will recover with great effort.",
    8: "You'll be safe from the allegation quickly.",
    9: "You won't inherit from your wife as sole heir.",
    10: "Argue your case. You'll win. Fight it out."
  },
  76: {
    1: "You'll inherit from your mother.",
    2: "You won't inherit from your father. Don't hope for it.",
    3: "You'll be freed, but not just yet.",
    4: "You won't be harmed now, but after a time.",
    5: "Don't rear the baby. I counsel you.",
    6: "You'll be in peril with regard to the accusation.",
    7: "You'll give an accounting with insolence.",
    8: "The traveler won't return. He's busy.",
    9: "You'll now pay back what you owe as a result of your efforts.",
    10: "You won't be able to borrow money just yet. Someone doesn't trust you."
  },
  77: {
    1: "Your lot won't stay with you.",
    2: "You'll become a decemvir in a way you don't know.",
    3: "You'll be able to see your homeland suddenly.",
    4: "You'll finish what you undertake and you'll be distinguished.",
    5: "You won't get a bequest. Don't hope for it.",
    6: "You haven't been poisoned. Don't be afraid; pray instead.",
    7: "You'll be estranged from your wife to your benefit.",
    8: "The fugitive won't escape your detection; you'll stumble onto him.",
    9: "You'll be a senator, but not just yet.",
    10: "You'll be an ambassador by yourself and you'll be very distinguished."
  },
  78: {
    1: "You're going to see a death that you don't want.",
    2: "You won't win just now. Be patient; it will benefit you.",
    3: "You won't have an inheritance just now. Be silent. You won't profit at all.",
    4: "You'll take a lease and profit as much as you desire.",
    5: "You'll be an oikonomos presently. No one is hindering you.",
    6: "She won't miscarry. Don't be afraid at all.",
    7: "Lend the money with collateral and you won't lose it.",
    8: "You won't sell your cargo quickly. Don't hurry.",
    9: "You'll be released from detention contrary to expectations.",
    10: "You won't get the woman you desire. It's to your advantage."
  },
  79: {
    1: "It's not to your advantage to enter an agreement.",
    2: "You'll go out of town suddenly and for some time.",
    3: "You won't advance just yet. You're hindered by others.",
    4: "You'll share well in the business and be grateful.",
    5: "You'll serve in the army and advance quickly.",
    6: "Inquire in the sixth hour and you'll hear the truth.",
    7: "You'll sail well after being delayed.",
    8: "The one who is detained will be set free with effort.",
    9: "You'll be reconciled with your wife very soon.",
    10: "You'll become a bishop after a long while."
  },
  80: {
    1: "You'll remain where you're going.",
    2: "You won't get provisions just now. Don't expect it.",
    3: "You'll get your entire deposit back.",
    4: "You'll marry your girlfriend. You'll be without care.",
    5: "Put down a deposit because you'll win.",
    6: "You'll have hope of trust and very excellent hope.",
    7: "You'll get the call to office very quickly.",
    8: "You won't be reinstated as a cleric. Do something else.",
    9: "You won't be a general just now. Don't expect it.",
    10: "You're going to see a death that is hurtful."
  },
  81: {
    1: "You'll be estranged from your wife.",
    2: "The fugitive won't escape your detection; you'll stumble onto him.",
    3: "You'll become a senator after a while and you'll suffer a loss.",
    4: "You'll be an ambassador by yourself and it won't benefit you.",
    5: "You won't be banished. Don't be afraid. Persevere.",
    6: "You'll be prosperous and you'll acquire many good things.",
    7: "You'll buy the thing you have in mind and then sell it.",
    8: "You won't be able to sell in the way you want.",
    9: "Your belongings will be sold at auction presently. Be concerned.",
    10: "You won't profit from the undertaking."
  },
  82: {
    1: "Don't share in the business. It's not to your advantage.",
    2: "You'll serve in the army, but not to your advantage.",
    3: "You'll work, laboring for the good, and you'll take pleasure.",
    4: "You'll sail unexpectedly and well.",
    5: "The one who is detained won't be set free.",
    6: "You won't be estranged from your girlfriend for many reasons.",
    7: "You'll become a bishop after you've taken great pains.",
    8: "You won't be caught in adultery. Don't be afraid.",
    9: "You'll buy land with your toil.",
    10: "You won't remain an elder."
  },
  83: {
    1: "You won't be released from detention.",
    2: "You'll get the woman you desire and you'll be her guardian.",
    3: "He'll recover quickly from the illness, if you're attentive.",
    4: "You won't be safe from the allegation although you have had great influence.",
    5: "You won't inherit from your wife. It's granted to someone else.",
    6: "If you present your case, you'll win. Fight it out.",
    7: "A little of your property will remain in your possession.",
    8: "You'll get the dowry and waste it.",
    9: "You won't inherit from your parents. It's granted to someone else.",
    10: "You won't beget children just yet. Wait."
  },
  84: {
    1: "You won't have a benefit in your friend.",
    2: "You'll be purchased and it will go well for you with those to whom you're sold.",
    3: "You won't remain where you're going, since you won't be the first.",
    4: "You won't get provisions just now.",
    5: "You'll get your deposit back.",
    6: "You'll marry your girlfriend and she won't stay with you.",
    7: "If you put down a deposit, you'll lose it since you'll be defeated.",
    8: "You'll have excellent hope of trust.",
    9: "You'll get the call to office for which you yearn.",
    10: "You'll be made a cleric after a while. Don't be fainthearted."
  },
  85: {
    1: "Your belongings will be sold at auction.",
    2: "You'll profit from the undertaking a little.",
    3: "The traveler is alive and will return.",
    4: "You'll get part of the money.",
    5: "You'll get an escort.",
    6: "You'll be restored to your place very soon.",
    7: "You'll have dealings with another and profit a great deal.",
    8: "You won't have any benefit from your friend.",
    9: "You'll be sold and you'll be set free.",
    10: "You'll remain where you're going."
  },
  86: {
    1: "Don't lend anything.",
    2: "You'll sell your cargo quickly.",
    3: "You won't be released from detention just yet.",
    4: "You'll get the woman you desire.",
    5: "The sick person will be ill for a long time, but he'll regain his health.",
    6: "You'll be safe from the allegation, if you're attentive.",
    7: "You'll inherit from your wife, but not as the sole heir.",
    8: "You'll win the case, if you work to the end.",
    9: "Not all of your property will remain in your possession.",
    10: "You'll get the dowry after you've fought many battles."
  },
  87: {
    1: "You won't find a way to sell your goods.",
    2: "Your belongings won't be sold at auction. Don't worry.",
    3: "You won't profit from the undertaking.",
    4: "The traveler isn't alive. Don't expect him.",
    5: "You'll get a small part of the money.",
    6: "You won't get an escort just now. Count on it.",
    7: "You'll be restored to your place with joy.",
    8: "If you have dealings with another, you'll be harmed a great deal.",
    9: "You'll have a great benefit from your friend.",
    10: "You won't be sold, but you'll be set free with a bequest."
  },
  88: {
    1: "You'll advance well.",
    2: "Don't share in the business. It's not to your advantage.",
    3: "You'll serve in the army and advance quickly.",
    4: "You'll work, envied by the crowd.",
    5: "At length the marriage will be finalized out of necessity.",
    6: "The one who is detained will be set free.",
    7: "You'll be estranged from your girlfriend because of jealousy.",
    8: "You'll become a bishop, but not just yet. Wait.",
    9: "You won't be caught as an adulterer just now. Take heed.",
    10: "You won't buy land or a house."
  },
  89: {
    1: "You'll become a decemvir.",
    2: "You'll be able to see your homeland and to rejoice.",
    3: "You'll finish what you undertake.",
    4: "You'll get a large bequest, if you take heed.",
    5: "You've indeed been poisoned. Treat yourself.",
    6: "You won't be estranged from your wife in a good way.",
    7: "The fugitive will escape your detection up to a point.",
    8: "You'll be a senator and you'll profit so as to become wealthy.",
    9: "You'll be an ambassador and you'll profit in the matter.",
    10: "You'll be banished and you'll be treated humanely in the matter."
  },
  90: {
    1: "You'll marry your girlfriend presently.",
    2: "Put down a deposit because you'll win. Be cheerful.",
    3: "You won't have hope of trust at all.",
    4: "You'll get the call to office for which you've prayed.",
    5: "You'll be made a cleric and you'll become a pest.",
    6: "You'll be a general and thrive until the end.",
    7: "You're going to see a death at home very soon, but persevere.",
    8: "You won't win. Don't do battle at all.",
    9: "You'll have an inheritance and suffer a great financial loss.",
    10: "If you take a lease, you'll suffer a great loss."
  },
  91: {
    1: "You'll be able to go out of town presently.",
    2: "You won't advance now. Stop imagining.",
    3: "Don't share in the business. It's not to your advantage. You'll suffer losses.",
    4: "You'll serve in the army and suffer greatly.",
    5: "If you work, you'll derive great benefit and you'll profit.",
    6: "You'll sail with danger, but be brave.",
    7: "The one who is detained will be set free in time.",
    8: "You'll make up with your girlfriend and you'll be harmed.",
    9: "You'll become a bishop after a while.",
    10: "You won't be caught as an adulterer. Don't be distressed."
  },
  92: {
    1: "Enter an agreement. You'll benefit.",
    2: "If you go out of town, you'll suffer.",
    3: "You'll advance just as you have prayed.",
    4: "It's not to your advantage to share in the business.",
    5: "You won't serve in the army. Don't expect to.",
    6: "Inquire with fear and you'll hear the truth.",
    7: "You'll sail, but not just yet.",
    8: "The one who is detained will be in danger and will die.",
    9: "Your girlfriend won't become estranged, since she's being fed.",
    10: "You won't be able to be a bishop. Don't expect it."
  },
  93: {
    1: "You won't go out of town now.",
    2: "You'll advance suddenly when you don't realize it.",
    3: "You'll share in the business to your detriment.",
    4: "You won't serve in the army just yet. Why are you in a hurry?",
    5: "If you're inquiring in good faith, inquire.",
    6: "You'll sail after being delayed, and it will be to your advantage.",
    7: "The one who is detained will be set free.",
    8: "You'll be reconciled with your wife and you'll be sorry.",
    9: "You'll become a bishop after a while.",
    10: "You won't be caught as an adulterer now, but you will be later."
  },
  94: {
    1: "You won't sell your cargo just yet.",
    2: "You'll be released from detention.",
    3: "You won't get the woman you desire.",
    4: "He'll recover quickly from his illness.",
    5: "You won't be safe from the allegation. Be careful.",
    6: "You'll inherit from your wife.",
    7: "Argue your case. You'll win in accordance with the truth.",
    8: "Your property will remain in your possession.",
    9: "You'll get the dowry in part.",
    10: "You won't inherit from your parents. You'll die first."
  },
  95: {
    1: "Put down a deposit. You'll win.",
    2: "You'll have hope of trust.",
    3: "You'll get the call to office.",
    4: "You'll be made a cleric after a time.",
    5: "It won't benefit you to be a general.",
    6: "You're not going to see a death just now.",
    7: "You won't win. Keep silent.",
    8: "You'll have an inheritance, but not as sole heir.",
    9: "If you take a lease, you'll suffer a loss.",
    10: "You'll be a trusted oikonomos and you'll be distinguished."
  },
  96: {
    1: "You won't inherit from your friend.",
    2: "You won't have a good end. Help yourself.",
    3: "You'll find the fugitive immediately and you won't be vexed.",
    4: "You won't be an official now. Why are you expecting it?",
    5: "You'll inherit from your mother, but not as sole heir.",
    6: "You won't be the only heir of your father.",
    7: "You'll be freed after some time, but don't be distressed.",
    8: "You won't be harmed. Don't be distressed, but take heart.",
    9: "The baby will die, not live.",
    10: "You'll be safe from the accusation after a little while."
  },
  97: {
    1: "You'll succeed happily.",
    2: "You won't enter an agreement. Wait for the time being.",
    3: "You won't go out of town soon, because you're hindered.",
    4: "You'll advance and you'll be successful in a hurry.",
    5: "You'll share in the business, but it won't benefit you, since you'll suffer a loss.",
    6: "You'll serve in the army now and benefit greatly.",
    7: "Consult with a pure conscience.",
    8: "You'll sail after being delayed.",
    9: "The one who is detained will be set free from his confinement.",
    10: "You'll be estranged from your girlfriend. She's acting foolishly. It will benefit you."
  },
  98: {
    1: "You'll share in the business and suffer.",
    2: "You won't serve in the army now. Wait.",
    3: "It's not time for consultation.",
    4: "You won't sail now, because you're not ready.",
    5: "The one who is detained won't be set free.",
    6: "You won't be estranged from your girlfriend.",
    7: "You'll become a bishop, if you have love.",
    8: "You'll be found to be an adulterer, but you'll come through safely.",
    9: "You'll buy property or a house as a result of your own efforts.",
    10: "You'll remain an elder until death."
  },
  99: {
    1: "You won't open a workshop.",
    2: "You won't recover from your sickness. You'll die.",
    3: "You'll become a teacher suddenly and you'll be distinguished.",
    4: "You'll find what is lost, but it will take some time.",
    5: "You'll be an agoranomos, but not just yet. Why are you so eager?",
    6: "You won't inherit from your friend.",
    7: "You won't have a good end, but a painful one.",
    8: "You won't find the fugitive.",
    9: "You won't be an official now in the matters you desire. Don't expect it.",
    10: "You won't inherit from your mother. Don't hope for it."
  },
  100: {
    1: "You won't get the dowry.",
    2: "You won't inherit from your parents. You'll die first.",
    3: "You'll beget children, but not just yet. Wait.",
    4: "You won't come to terms with your masters. It's not to your advantage.",
    5: "You'll obtain your petition for what you need.",
    6: "You won't have a long life.",
    7: "You'll open a workshop with short notice.",
    8: "You'll recover from your sickness. Don't be distressed.",
    9: "You'll be a teacher with great honor.",
    10: "You'll never find what is lost."
  },
  101: {
    1: "Consult only once in the third hour.",
    2: "You'll sail, but you'll be delayed in the undertaking.",
    3: "You'll serve in the army and be very sorry.",
    4: "You'll share in the business and suffer many losses.",
    5: "You won't be able to advance just yet. You're being hindered.",
    6: "You'll go out of town, where you desire, for your good.",
    7: "You'll succeed as a consequence of many fine efforts.",
    8: "Don't enter the agreement, because you'll suffer greatly.",
    9: "You'll purchase what is offered.",
    10: "You won't marry just yet. Wait."
  },
  102: {
    1: "You'll soon be safe from the accusation.",
    2: "You'll soon give an accounting to your benefit.",
    3: "The traveler won't return. He's hindered.",
    4: "You won't pay back just yet what you owe.",
    5: "You'll borrow money and you won't suffer a loss. You'll profit.",
    6: "You'll father a baby, but the baby will be unprofitable.",
    7: "You won't move from your place. Don't be distressed.",
    8: "You can be harmed a little. Don't be distressed.",
    9: "You'll marry and you'll be distressed, because you'll be filled with regret.",
    10: "You won't purchase what is offered. You won't be able to."
  },
  103: {
    1: "You won't be made a cleric.",
    2: "You won't become a bishop. Don't wait for it.",
    3: "You'll be found to be an adulterer after much time.",
    4: "You won't buy land or a house.",
    5: "You won't remain an elder. Despise yourself.",
    6: "Your wife will stay with you, because she has self-control.",
    7: "You'll get free from your lot in a hurry.",
    8: "You'll become a decemvir and be distinguished.",
    9: "You won't set eyes on your homeland.",
    10: "(text missing)"
  }
};
